# Anjana Nallanagula
# AP19110010340
# SRM University

# Task
* Create arrays with all the data types available in numpy

* Integer

In [1]:
import numpy as np
a = np.array([1, 2, 3, 4], dtype = 'int_')
print(a)
print(a.dtype)

[1 2 3 4]
int32


* Boolean

In [2]:
a = np.array([True, False, False, True], dtype = 'bool_')
print(a)
print(a.dtype)

[ True False False  True]
bool


* Float

In [3]:
a = np.array([1.6, 2.9, 3.3, 4.6], dtype = 'float_')
print(a)
print(a.dtype)

[1.6 2.9 3.3 4.6]
float64


* Complex

In [4]:
a = np.array([1+3j, 2+4j, 6+8.7j, 8+3.4j], dtype = 'complex_')
print(a)
print(a.dtype)

[1.+3.j  2.+4.j  6.+8.7j 8.+3.4j]
complex128


* String

In [5]:
a = np.array(['a', 'b', 'c', 'd'], dtype = 'S')
print(a)
print(a.dtype)

[b'a' b'b' b'c' b'd']
|S1


* Object

In [6]:
a = np.array([[1, 2], [3, 4], [4.6, 7.4], ['chandler', 'jake']], dtype = 'O')
print(a)
print(a.dtype)

[[1 2]
 [3 4]
 [4.6 7.4]
 ['chandler' 'jake']]
object


* Unicode

In [7]:
a = np.array([1, 2, 3, 4], dtype = 'U')
print(a)
print(a.dtype)

['1' '2' '3' '4']
<U1


* Unsigned integer

In [8]:
a = np.array([1, 2, 3, 4], dtype = 'uint8')
print(a)
print(a.dtype)

[1 2 3 4]
uint8


* Datetime

In [9]:
a = np.array(['2001-01-01T12:00', '2002-02-03T13:56:03.172'], dtype = 'M')
print(a)
print(a.dtype)

['2001-01-01T12:00:00.000' '2002-02-03T13:56:03.172']
datetime64[ms]


* Timedelta

In [11]:
a = np.timedelta64(4, 'Y')
print(a)
print(a.dtype)

4 years
timedelta64[Y]


* Void

In [13]:
a = np.void([], dtype = 'V')
print(a)
print(a.dtype)

[]
|V8
